version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hms_user
      POSTGRES_PASSWORD: hms_password
      POSTGRES_DB: hmsdb
    ports:
      - "5432:5432"          # so you can connect with PgAdmin if you like
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hms_user -d hmsdb"]
      interval: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Dormie-Backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"          # localhost:8080 → container:8080
    depends_on:
      db:
        condition: service_healthy
    # Remove problematic volume mounts that interfere with compiled application
    # volumes:                 # for live-reload during coding
    #   - ./Dormie-Backend/src:/app/src
    #   - ~/.m2:/root/.m2

  frontend:
    build:
      context: ./Dormie-Frontend
      target: development     # Use the development stage for dev environment
    command: ["pnpm", "run", "dev"]   # ← exec form (array), no /bin/sh
    ports:
      - "3000:3000"          # localhost:3000 → container:3000
    depends_on:
      - backend
    volumes:                 # for live-reload during coding
      - ./Dormie-Frontend:/app
      - /app/node_modules    # anonymous volume to prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # for better file watching in Docker

volumes:
  postgres_data:
