version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hms-postgres
    # No ports exposed ⇒ DB reachable only inside Docker network
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env                       # pulls POSTGRES_* vars
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [hms-network]

  backend:
    image: ghcr.io/mushfiqur6087/hms-backend:latest
    container_name: hms-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"                # public API
    env_file:
      - .env                       # pulls SPRING_*, JWT_*, etc.
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks: [hms-network]

volumes:
  db_data:

networks:
  hms-network:
    driver: bridge
