name: Build & Push Backend
on:
  push:
    branches: [master]           # change to master if needed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write          # allow push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up repository name
        id: repo
        run: |
          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.REPO_OWNER_LC }}/hms-backend:latest
            ghcr.io/${{ steps.repo.outputs.REPO_OWNER_LC }}/hms-backend:${{ github.sha }}
